parameters:
   core.event.subscriber.timestampable_subscriber.class: 'Azhuro\Bundle\CoreBundle\Event\Subscriber\TimestampableSubscriber'

services:
    core.event.subscriber.timestampable_subscriber:
        class: '%core.event.subscriber.timestampable_subscriber.class%'
        tags:
            - { name: doctrine.event_subscriber }